apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: tams
  labels:
    app: kafka
    app.kubernetes.io/part-of: tams
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.8.0
          ports:
            - name: broker
              containerPort: 9092
            - name: controller
              containerPort: 9093
          envFrom:
            - configMapRef:
                name: kafka-config
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - kafka-topics
                - --bootstrap-server
                - localhost:9092
                - --list
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - kafka-topics
                - --bootstrap-server
                - localhost:9092
                - --list
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
