apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: tams
  labels:
    app: auth-service
    app.kubernetes.io/part-of: tams
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
