apiVersion: v1
kind: Service
metadata:
  name: parser-service
  namespace: tams
  labels:
    app: parser-service
    app.kubernetes.io/part-of: tams
spec:
  type: ClusterIP
  selector:
    app: parser-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
