apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-rules-data
  namespace: tams
  labels:
    app: postgres-rules
    app.kubernetes.io/part-of: tams
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
