apiVersion: v1
kind: Service
metadata:
  name: postgres-analysis
  namespace: tams
  labels:
    app: postgres-analysis
    app.kubernetes.io/part-of: tams
spec:
  type: ClusterIP
  selector:
    app: postgres-analysis
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
