apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tams
  labels:
    app: frontend
    app.kubernetes.io/part-of: tams
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
